version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: recipe_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - recipe_net

  db:
    image: mysql:5.7
    container_name: recipe_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: recipe_db
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
    ports:
      - 3311:3306
    networks:
      - recipe_net

  nginx:
    image: nginx:alpine
    container_name: recipe_nginx
    restart: unless-stopped
    ports:
      - 8087:80
    links:
      - app
      - db
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - recipe_net

networks:
  recipe_net:
    driver: bridge
