export const AUTH = {
    AUTH_LOGIN: "AUTH_LOGIN",
    AUTH_LOGOUT: "AUTH_LOGOUT",
    AUTH_REFRESH_TOKEN: "AUTH_REFRESH_TOKEN",
    FETCH_AUTH: "FETCH_AUTH",
    SET_CALLBACK_URL: "SET_CALLBACK_URL"
  };


  export const CATEGORY = {
    GET_CATEGORY_LIST : "GET_CATEGORY_LIST",
    FETCH_CATEGORY_LIST: "FETCH_CATEGORY_LIST",
  };

  export const COMMON = {
    USER_INFO: "USER_INFO"
  }
