export const AUTH = {
    AUTH_LOGIN: "AUTH_LOGIN",
    AUTH_LOGOUT: "AUTH_LOGOUT",
    AUTH_REFRESH_TOKEN: "AUTH_REFRESH_TOKEN",
    FETCH_AUTH: "FETCH_AUTH",
    SET_CALLBACK_URL: "SET_CALLBACK_URL"
  };


  export const CATEGORY = {
    GET_CATEGORY_LIST : "GET_CATEGORY_LIST",
    FETCH_CATEGORY_LIST: "FETCH_CATEGORY_LIST",
    GET_CATEGOTY_DETAIL: "GET_CATEGOTY_DETAIL",
    
  };

  export const POST = {
    GET_POST_LIST : "GET_POST_LIST",
    GET_POST_DETAIL: "GET_POST_DETAIL",
    GET_POST_APPROVED: "GET_POST_APPROVED",
    GET_ALL_POST: "GET_ALL_POST",
    GET_POST_DETAIL_USER: "GET_POST_DETAIL_USER",
    GET_MY_POST: "GET_MY_POST",

  };

  export const FAVOURITE = {
    SUBMIT: "SUBMIT",
  }


  export const RATE = {
    RATE_POST_LIST: "RATE_POST_LIST",
  }


  export const INGREDIENT = {
    GET_INGREDIENT_LIST : "GET_INGREDIENT_LIST",
  }

  export const DIRECTION = {
    GET_DIRECTION_LIST : "GET_DIRECTION_LIST",
  }

  export const POST_IMAGE = {
    GET_POST_IMAGE_LIST : "GET_POST_IMAGE_LIST",
  }

  export const COMMON = {
    USER_INFO: "USER_INFO"
  }
